name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # TODO: add a build step here
      - uses: actions/checkout@v3.0.0
      - uses: erlef/setup-beam@v1.13.0
        with:
          otp-version: "25.1"
          gleam-version: "0.24.0"
          # elixir-version: "1.14.1"

      - run: gleam deps download
      - run: gleam build --target=javascript && cp -r ./static ./build/dev/javascript/brettooo/dist

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "brett-ooo"
          entrypoint: "./build/dev/javascript/brettooo/dist/entry.js" # TODO: update entrypoint

